[package]
name = "stellar-access"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
publish = true
description = "Access Control, Ownable, and Role Transfer utilities for Stellar contracts."

[features]
default = ["ownable", "roles"]
ownable = []
roles = []

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
stellar-event-assertion = { workspace = true }
