[package]
name = "stellar-tokens"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
version.workspace = true
description = "Fungible and NonFungible Tokens for the Stellar contracts."

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[features]
default = []
fungible = []
non-fungible = []
burnable = []
sac = ["fungible"]
pausable = ["stellar-contract-utils/pausable"]
rwa = ["fungible", "pausable"]
vault = ["fungible", "stellar-contract-utils/math"]
allowlist = ["fungible", "burnable"]
blocklist = ["fungible", "burnable"]
capped = ["fungible"]
votes = ["dep:stellar-governance", "burnable"]
enumerable = ["non-fungible", "burnable"]
consecutive = ["non-fungible", "burnable"]
royalties = ["non-fungible"]

[dependencies]
soroban-sdk = { workspace = true }
stellar-contract-utils = { workspace = true }
stellar-governance = { workspace = true, optional = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-test-helpers = { workspace = true }
stellar-event-assertion = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
p256 = { workspace = true, features = ["ecdsa"] }
