[package]
name = "stellar-tokens"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
version.workspace = true
description = "Fungible and NonFungible Tokens for the Stellar contracts."

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
cvlr = { workspace = true, default-features = false }
cvlr-soroban = { workspace = true }
cvlr-soroban-macros = { workspace = true }
cvlr-soroban-derive = { workspace = true }
stellar-contract-utils = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-test-helpers = { workspace = true }
stellar-event-assertion = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
p256 = { workspace = true, features = ["ecdsa"] }

[features]
certora  = ["stellar-contract-utils/certora"]