[package]
name = "stellar-tokens"
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = true
version.workspace = true
description = "Fungible and NonFungible Tokens for the Stellar contracts."

[features]
default = ["fungible", "non-fungible", "vault", "rwa"]
fungible = []
non-fungible = []
vault = ["fungible", "stellar-contract-utils/math"]
rwa = ["fungible", "stellar-contract-utils/pausable"]

[lib]
crate-type = ["lib", "cdylib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }
stellar-contract-utils = { workspace = true }

[dev-dependencies]
ed25519-dalek = { workspace = true }
soroban-sdk = { workspace = true, features = ["testutils"] }
soroban-test-helpers = { workspace = true }
stellar-event-assertion = { workspace = true }
k256 = { workspace = true, features = ["ecdsa"] }
p256 = { workspace = true, features = ["ecdsa"] }
